name: TcBuild test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, twincat, windows]
    steps:
      - uses: actions/checkout@v4

      - name: Build MONETcommon.sln
        shell: powershell
        run: |
          & "C:\Program Files\Industrial Brains B.V\TcBuild\TcBuild.exe" build MONETcommon.sln
